// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'abilities': string;
  'ability': string;
  'bug': string;
  'card': string;
  'container': string;
  'description': string;
  'fire': string;
  'flying': string;
  'grass': string;
  'imageContainer': string;
  'infoContainer': string;
  'label': string;
  'poison': string;
  'root': string;
  'statItem': string;
  'statValue': string;
  'statsContainer': string;
  'statsWrapper': string;
  'titleName': string;
  'types': string;
  'water': string;
}
export const cssExports: CssExports;
export default cssExports;
